### ISSUE TITLE
Конфигурация rispo_yandex_kassa в файле app/config.yml недоступна для Rispo/YandexKassaBundle

### ISSUE THREAD

**Issue by VitalyVesyolko** [rispo-service/RispoYandexKassaBundle#1]
Если выполнять установку и настройку Rispo/YandexKassaBundle согласно https://github.com/rispo-service/RispoYandexKassaBundle/blob/master/Resources/doc/index.ru.rst, то первая инструкция из раздела "Настройки", очевидно, требует коррекции.

Переменные rispo_yandexkassa_shopId, rispo_yandexkassa_scid, rispo_yandexkassa_ShopPassword, rispo_yandexkassa_test под секцией rispo_yandex_kassa в файле app/config.yml недоступны в файле vendor/rispo/yandexkassa-bundle/Rispo/YandexKassaBundle/Resources/config/services.yml после установки его вместе с зависимостями. Появляется ошибка: "[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                       
  The service "rispo.yandexkassa.client" has a dependency on a non-existent parameter "rispo_yandexkassa_shopid". Did you mean this: "rispo.yandexk  
  assa.class"?"
при попытке выполнить консольные команды, например, bin/console server:start.

Если эти переменные определить непосредственно в файле vendor/rispo/yandexkassa-bundle/Rispo/YandexKassaBundle/Resources/config/services.yml, то ошибка не возникает, поскольку переменные доступны беспрепятственно.

Но, поскольку при очередной установке пакетов через composer вся пользовательская конфигурация пакетов, находящихся в директории vendor будет утеряна, эти переменные каждый раз нужно будет восстанавливать в файл vendor/rispo/yandexkassa-bundle/Rispo/YandexKassaBundle/Resources/config/services.yml. Прошу исправить баг или скорректировать инструкцию по настройке бандла.

Баг обнаружен в проекте, основанном на Sulu CMS (Symfony-based fork).

**Comment by rispo-service** [comment]
Да, проблема есть. Поправим.

**Comment by svscorp** [comment]
@RiverFisher я бы не сказал, что это баг.

Попробуйте в `config.yml` вписать:
```
rispo_yandex_kassa:
    rispo_yandexkassa_shopId: %rispo_yandexkassa_shopId%
    rispo_yandexkassa_scid: %rispo_yandexkassa_shopId%
    rispo_yandexkassa_ShopPassword: %rispo_yandexkassa_ShopPassword%
    rispo_yandexkassa_test: %rispo_yandexkassa_test%
```

и в `parameters.yml` вписать нужные вам значения.
